#!/usr/bin/env bash
#Install nginx web server with redirect and 404 page
sudo apt-get update
sudo apt-get install nginx -y
echo "server {
    listen 80 ;
    listen [::]:80;
    root /var/www/html;
    index index.html;
    servername ;
    location / {
        try_files $uri $uri/ =404;
    }
}" > /etc/nginx/sites-available/default
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx restart
